version: '1.0'

networks:
    laravel:

services:
    app-nginx:
        build:
            context: ./dockerfiles
            dockerfile: nginx.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "80:80"
        volumes:
            - .:/var/www
        depends_on:
            - php
        networks:
            - laravel

    php:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www
        networks:
            - laravel
